defaults:
  - schedule: growing

device: "cuda:0"
learning_rate: 0.1
batch_size: 64
gca_batches: 4
betas: [0.9, 0.98]
eps: 1e-06
weight_decay: 0.01
use_onecycle: True
growth_phases: 0
tune_direction: True
tune_step_size: True
selection_method: "firefly"
grow_data_split: 0.1
