defaults:
  - schedule: growing
  - _self_

learning_rate: 1e-4
batch_size: 128
gca_batches: 2
betas: [0.9, 0.98]
eps: 1e-06
weight_decay: 0.01
gradient_clipping: 1.0
mlm_probability: 0.15
tune_direction: True
tune_step_size: True
selection_method: "firefly"
grow_data_portion: 0.1
grow_tune_params:
  batch_size: 32
  gca_batches: 8
  use_onecycle: True
  learning_rate: 6e-4
  weight_decay: 0.01
  betas:
    - 0.9
    - 0.98
