defaults:
  - schedule: static
  - _self_


learning_rate: 5e-5
batch_size: 64
gca_batches: 4
betas: [0.9, 0.98]
eps: 1e-06
weight_decay: 0.01
gradient_clipping: 1.0
mlm_probability: 0.15
tune_direction: True
tune_step_size: True
selection_method: "firefly"
grow_data_portion: 0.1
grow_tune_params: {}
