steps:
  - lr_scheduler:
      type: linear
      warmup_portion: 0.06
  - train:
      num_epochs: 2
  - checkpoint
  - train:
      num_epochs: 2
  - checkpoint
  - train:
      num_epochs: 2
  - checkpoint
  - train:
      num_epochs: 2
  - checkpoint
  - train:
      num_epochs: 2
